// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserInfo22 = "user_info22"

// UserInfo22 mapped from table <user_info22>
type UserInfo22 struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name         string         `gorm:"column:name" json:"name"`
	Age          int64          `gorm:"column:age" json:"age"`
	Birthday     time.Time      `gorm:"column:birthday" json:"birthday"`
	Email        string         `gorm:"column:email" json:"email"`
	Role         string         `gorm:"column:role" json:"role"`
	MemberNumber string         `gorm:"column:member_number;not null" json:"member_number"`
	Num          int32          `gorm:"column:num" json:"num"`
	Address      string         `gorm:"column:address" json:"address"`
}

// TableName UserInfo22's table name
func (*UserInfo22) TableName() string {
	return TableNameUserInfo22
}
