// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeEvent(ctx *gin.Context) Event {
	message := NewMessage(ctx)
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event
}
